version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore
    schedule:
      interval: daily
    labels:
      - kind/chore
    # reviewers:
    #   - appkins-org/admin

  - package-ecosystem: terraform
    registries: "*"
    directory: /
    groups:
      terraform:
        patterns:
          - "*"
    commit-message:
      prefix: chore
    schedule:
      interval: daily
    labels:
      - kind/chore
    # reviewers:
    #   - appkins-org/admin
